image:
  file: .gitpod.Dockerfile
ports:
  - port: 3306
    onOpen: ignore
  - port: 8001
    onOpen: open-preview
    
tasks:
  - name: Apache
    command: >
      apachectl start;
  - name: Open-Browser
    command: >
      gp open public/index.php;
  - name: php-login
    command: >
      mysql -u root -Bse "CREATE DATABASE IF NOT EXISTS auth;CREATE USER IF NOT EXISTS newuser@localhost IDENTIFIED BY 'password';GRANT ALL PRIVILEGES ON auth.* TO newuser@localhost;FLUSH PRIVILEGES;";mysql -u root auth < ./public/database.sql;sudo apt install php-mysql -y;
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client